### ISSUE TITLE
没有同步，也不报错。

### ISSUE THREAD

**Issue by go-lazyer** [liuxinwang/go-mysql-starrocks#1]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/8188533/233524343-baec6ed3-50f1-4abe-a638-f4ae164e0222.png">

**Comment by liuxinwang** [comment]
脱敏后的配置信息发一下

**Comment by go-lazyer** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/8188533/233537563-629c87da-26f4-4fac-a5e3-7d766fcbcb0b.png">

**Comment by go-lazyer** [comment]
mysql 数据库必须开启 gtid吗？我没开启，是不是这个原因。

**Comment by liuxinwang** [comment]
> mysql 数据库必须开启 gtid吗？我没开启，是不是这个原因。
是的，需要开启gtid

**Comment by liuxinwang** [comment]
> mysql 数据库必须开启 gtid吗？我没开启，是不是这个原因。

是的，需要开启gtid
