### ISSUE TITLE
一个文件同步了九张表启动报错，组件有限制表个数么

### ISSUE THREAD

**Issue by yangxue1996** [liuxinwang/go-mysql-starrocks#10]
panic: runtime error: index out of range [23] with length 23

goroutine 4 [running]:
github.com/go-mysql-org/go-mysql/canal.(*RowsEvent).handleUnsigned(0xc0000c2000)
        /Users/wangwuyang/GolandProjects/pkg/mod/github.com/go-mysql-org/go-mysql@v1.6.0/canal/rows.go:56 +0x5c5
github.com/go-mysql-org/go-mysql/canal.newRowsEvent(0xc000308100, {0xa66468, 0x6}, {0xc000284900, 0x2, 0x2e}, 0xc00061bfc8)
        /Users/wangwuyang/GolandProjects/pkg/mod/github.com/go-mysql-org/go-mysql@v1.6.0/canal/rows.go:39 +0xe8
github.com/go-mysql-org/go-mysql/canal.(*Canal).handleRowsEvent(0xc000362000, 0xc0004fed20)

**Comment by liuxinwang** [comment]
用的哪个版本
