### ISSUE TITLE
怎加了啥新功能吗？启动文件变的这么大。

### ISSUE THREAD

**Issue by go-lazyer** [liuxinwang/go-mysql-starrocks#11]
<img width="699" alt="image" src="https://github.com/liuxinwang/go-mysql-starrocks/assets/8188533/0eb24faf-d0b9-4ba4-8658-12049a9c84cb">

**Comment by liuxinwang** [comment]
增加了vm memory mysql server（dolthub/go-mysql-server），用于保存每次的ddl操作，用于回溯历史；废弃了meta.info文件。
另外，从较早的版本升级到最新，需要注意点位保存从pos.info改为了源端数据库(_go_mysql_sr)，需要看一下历史版本是否兼容

**Comment by go-lazyer** [comment]
哎，越来越臃肿了。

**Comment by go-lazyer** [comment]
加上 go-mysql-server 会吃多少服务器内存啊。

**Comment by liuxinwang** [comment]
> 加上 go-mysql-server 会吃多少服务器内存啊。

目前测试下来会多几十M内存。

**Comment by go-lazyer** [comment]
好吧，感觉使用SQLite 会好些，个人建议啊。还是喜欢之前简单的版本。功能不全，但是刚刚够用。

**Comment by liuxinwang** [comment]
> 好吧，感觉使用SQLite 会好些，个人建议啊。还是喜欢之前简单的版本。功能不全，但是刚刚够用。

sqlite不支持mysql语法，不过可以作为本地点位持久化存储库，现在把点位保存在源端数据库是为了方便程序迁移以及k8s部署等。v0.2.0及之前版本较简单，新版本api支持完善一些。
