### ISSUE TITLE
handling primary key not int type is not currently supported

### ISSUE THREAD

**Issue by running-db** [liuxinwang/go-mysql-starrocks#13]
请问，对于非int类的主键，有计划支持不。其实配置在配置文件中，他能增量同步，但是直接配置文件启动不支持全量同步。我使用api全量同步报错不支持非int主键。
另外我想咨询下，全量同步时加锁表之类的没有
```golang
		if !strings.Contains(primaryKeyDataType, "int") {
			log.Errorf("handling primary key not int type is not currently supported")
			return errors.New("handling primary key not int type is not currently supported")
		}
```

**Comment by liuxinwang** [comment]
给一个示例的主键值，我这边支持下；
全量同步会暂停当前同步线程，直到全量数据同步完成后会自动恢复同步，保证已有表增量和新增表全量+增量数据同步一致性。

**Comment by running-db** [comment]
> 给一个示例的主键值，我这边支持下； 全量同步会暂停当前同步线程，不会对源端表加锁；直到全量数据同步完成后会自动恢复同步，保证已有表增量和新增表全量+增量数据同步一致性。

感谢！！
+-----------------+
| order_id        |
+-----------------+
| R22110901218521 |
| R22110901218531 |
| R22110901218613 |
| R22110901218709 |
| R22110901218748 |
| R22110901218689 |
| R22110901218707 |
| R22110901218744 |
| R22110901219207 |
| R22110901219199 |
+-----------------+

**Comment by liuxinwang** [comment]
参考 [v0.4.0](https://github.com/liuxinwang/go-mysql-starrocks/releases/tag/v0.4.0)

**Comment by running-db** [comment]
> 参考 [v0.4.0](https://github.com/liuxinwang/go-mysql-starrocks/releases/tag/v0.4.0)

好的，太拼了，这么晚还在回。真.开源 热爱
