### ISSUE TITLE
starRock stream load 8030 为啥来接不上呢？

### ISSUE THREAD

**Issue by xiaoxuanfeng** [liuxinwang/go-mysql-starrocks#14]

**Comment by liuxinwang** [comment]
可以用telnet ip port 进行验证网络是否连通

**Comment by xiaoxuanfeng** [comment]
我尝试着 修改以下代码 让其可以并发执行，提高应用速度：
err = sr.Execute(schemaTableEvents[schemaTable], tableObj, ruleMap.TargetSchema, ruleMap.TargetTable)
					if err != nil {
						log.Fatalf("do starrocks bulk err %v, close sync", err)
						sr.cancel()
						return
					}
改成以下，但是执行是老是报错： [fatal] op_starrocks.go:158 do starrocks bulk err too many filtered rows
	wp.Add(1)
				go func() {
					defer wp.Done()
					err = sr.Execute(schemaTableEvents[schemaTable], tableObj, ruleMap.TargetSchema, ruleMap.TargetTable)
					if err != nil {
						log.Fatalf("do starrocks bulk err %v, close sync", err)
						sr.cancel()
						return
					}
				}()}
			// 等待多线程执行结束
			wp.Wait()
			for schemaTable := range schemaTableEvents {
				delete(schemaTableEvents, schemaTable)
			}


查看了报错链接：Error: NULL value in non-nullable column 'wellen_code'. 可以看出应该是数据错乱了，但改成原来的代码是没问题的，也查不出来啥原因，帮忙看下呢

**Comment by xiaoxuanfeng** [comment]
是通的，8030 是 FE 的 HTTP 默认端口号的，8040 是 BE 的默认 HTTP 端口号。 SR官方文档说这两个端口都可以执行strem load ,但你的代码 指定端口8030 包错：no valid Basic authorization 官方文档：https://docs.starrocks.io/zh/docs/sql-reference/sql-statements/data-manipulation/STREAM_LOAD

**Comment by liuxinwang** [comment]
port=${FE MySQL Server 端口}
load-port=${FE HTTP Server 端口}
你是这样配置的吗？

**Comment by xiaoxuanfeng** [comment]
是的

**Comment by xiaoxuanfeng** [comment]
是的，使用的是sr默认端口：
port = 9030
load-port = 8030

**Comment by liuxinwang** [comment]
好的， 我这边测试下

**Comment by xiaoxuanfeng** [comment]
你好 ，有进展没。

**Comment by liuxinwang** [comment]
近期修复，请耐心等待下

**Comment by liuxinwang** [comment]
参考[v0.4.4](https://github.com/liuxinwang/go-mysql-starrocks/releases/tag/v0.4.4)
