### ISSUE TITLE
请问下项目后续

### ISSUE THREAD

**Issue by bbpcer** [liuxinwang/go-mysql-starrocks#18]
你好，请问下项目后续规划是做什么呢，做web ui吗，有没有其他功能方面的优化，例如现在只能是从mysql主库同步数据，但生产更多的是要从从库同步数据而不影响主库的

**Comment by liuxinwang** [comment]
近期看一下，考虑增强修复。

**Comment by liuxinwang** [comment]
如果连接从库拉取binlog，那么还是需要一个可以写入的mysql作为meta记录点位等信息的数据库（_go_mysql_sr）

**Comment by bbpcer** [comment]
是的，简单改的话可以再增加一个配置项(mainDB)，在pos_mysql_v2的LoadPosition传入作为主要的元数据库，mainDB在生产可以配置为主库地址，source配置为从库地址

**Comment by liuxinwang** [comment]
参考[v0.4.5](https://github.com/liuxinwang/go-mysql-starrocks/releases/tag/v0.4.5)
