### ISSUE TITLE
请教下全量同步的原理，全量的如何接上增量的，类似mysqldump那样使用RR模式且加了--single-transaction么

### ISSUE THREAD

**Issue by running-db** [liuxinwang/go-mysql-starrocks#24]
还有一个疑问，为什么查询数据库要根据主键排序呢。

**Comment by liuxinwang** [comment]
1. 全量+增量逻辑
    暂停ouput写入 -> 添加新增表到binlog监听中 -> select全量同步操作 -> 恢复output
2. 现在使用的ExecuteSelectStreaming方法，不加也是可以的（但是正常全量同步都会按照主键排序进行分批查询，降低对数据库的影响）

**Comment by running-db** [comment]
是严格一致的么？有记录全量同步时的gtid没，用于全量同步完成后从此gtid开始增量同步？想了下，好像先记录binlog也没问题，早一点的binlog可以当作数据重复写入更新，已删除的数据，select也不会同步出来。

**Comment by liuxinwang** [comment]
> 是严格一致的么？有记录全量同步时的gtid没，用于全量同步完成后从此gtid开始增量同步？想了下，好像先记录binlog也没问题，早一点的binlog可以当作数据重复写入更新，已删除的数据，select也不会同步出来。

理论上是严格一致的，还没有发现不一致的情况。

**Comment by running-db** [comment]
好的，感谢热心解答
