### ISSUE TITLE
go-mysql-starrocks-manager-20241010231411点击”查看规则“报错：Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by running-db** [liuxinwang/go-mysql-starrocks#26]
您好，go-mysql-starrocks-manager与go-mysql-sr运行在同一台机器，在manager网页上点击 查看规则 时报错，报错文本为：
```
Something went wrong.
Cannot read properties of null (reading 'map')
```

日志等级为debug，manage.log内容：
```
[GIN] 2024/11/15 - 13:57:21 | 200 |    2.161007ms |      172.1.1.98 | GET      "/api/instance/config/query?host=127.0.0.1&port=6166"
```

![manager报错](https://github.com/user-attachments/assets/9ec3dc51-deef-47a2-b56f-a6ba26be0261)

**Comment by liuxinwang** [comment]
https://github.com/liuxinwang/go-mysql-starrocks/releases/download/v0.6.1/go-mysql-starrocks-manager-v0.0.2.tar.gz
