### ISSUE TITLE
亲，是否支持把 mysql 中vachar 转为 starrocks 中的json 字段

### ISSUE THREAD

**Issue by go-lazyer** [liuxinwang/go-mysql-starrocks#3]
亲，是否支持把 mysql 中vachar 转为 starrocks 中的json 字段

**Comment by liuxinwang** [comment]
能描述下具体场景吗

**Comment by go-lazyer** [comment]
我们mysql订单表中是用vachat 中存储一个json格式的字符串来保存购买的商品信息的。想在starrocks中解析jsoin 需要把改字段转给json格式。

**Comment by liuxinwang** [comment]
starrocks中parse_json 函数是否能满足你的需求呢？查询的时候可以通过parse_json解析为json

**Comment by go-lazyer** [comment]
亲，满足不了条件，需要在查询阶段就要解析json。 需要where 中使用。

**Comment by liuxinwang** [comment]
有具体的查询场景吗？ 目前来看通过函数转换后不影响where查询

**Comment by liuxinwang** [comment]
我写了一个filter 【convert-dml-column】用于处理json类型转换，可以满足这个需求；但目前需要一个有力的理由用于合并支撑这个需求。
