### ISSUE TITLE
您好，请问一下go-mysql-starrocks是否会同步binlog中删除的操作？

### ISSUE THREAD

**Issue by yangxue1996** [liuxinwang/go-mysql-starrocks#5]
使用同步软件后，starrocks同步的条数明显多于mysql中的条数，对于mysql的删除操作，同步软件会一并同步过来么？

**Comment by liuxinwang** [comment]
会同步delete操作，在2.4版本测试中，stream load导入需要sr表中是primary key模型才支持

**Comment by yangxue1996** [comment]
是指go-mysql-starrocs0.11版本也会同步delete操作么？但是目前使用情况是他并没有同步一些删除操作，另外2.4版本测试中这个打算什么时候上线呢

**Comment by liuxinwang** [comment]
目前0.11支持同步delete，你的表是用的primary key模型吗？给一个脱敏的表结构实例看看，包括mysql和sr

**Comment by yangxue1996** [comment]
mysql 版本8.0.23 MySQL  starrocks版本 StarRocks version 2.5.0
mysql 表结构CREATE TABLE   `aaa` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `a` VARCHAR(32) NOT NULL DEFAULT '' ,
    `c` VARCHAR(32) NOT NULL DEFAULT '' ,
    `b` VARCHAR(20) NOT NULL DEFAULT '' 
PRIMARY KEY (`id`),
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 

starrocks结构CREATE TABLE `aaa` (
    `id` BIGINT DEFAULT '0',
   `a` VARCHAR(32) NOT NULL DEFAULT '' ,
    `c` VARCHAR(32) NOT NULL DEFAULT '' ,
    `b` VARCHAR(20) NOT NULL DEFAULT ''
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 6;

**Comment by yangxue1996** [comment]
问一下此同步软件只能增量同步么？明显我使用情况是，开启同步进程后，只会同步进程开启时间后的增量数据，历史数据无法同步

**Comment by liuxinwang** [comment]
> 问一下此同步软件只能增量同步么？明显我使用情况是，开启同步进程后，只会同步进程开启时间后的增量数据，历史数据无法同步

是的，目前只能增量。历史数据暂时可以使用datax等进行同步。

**Comment by liuxinwang** [comment]
我这边测试是支持删除的，测试数据如下：
插入3条测试数据
```
-- mysql version 8.0.23

mysql> select * from aaa;
Empty set (0.00 sec)

mysql> insert into aaa(a,c,b)values('a','a','a');
Query OK, 1 row affected (0.00 sec)

mysql> insert into aaa(a,c,b)values('b','b','b');
Query OK, 1 row affected (0.00 sec)

mysql> insert into aaa(a,c,b)values('c','c','c');
Query OK, 1 row affected (0.01 sec)

mysql> select * from aaa;
+----+---+---+---+
| id | a | c | b |
+----+---+---+---+
|  4 | a | a | a |
|  5 | b | b | b |
|  6 | c | c | c |
+----+---+---+---+
3 rows in set (0.00 sec)
```

```
-- starrocks  2.5.6
mysql> select * from aaa order by id;
+------+------+------+------+
| id   | a    | c    | b    |
+------+------+------+------+
|    4 | a    | a    | a    |
|    5 | b    | b    | b    |
|    6 | c    | c    | c    |
+------+------+------+------+
3 rows in set (0.04 sec)
```

删除1条测试数据
```
-- mysql version 8.0.23

mysql> delete from aaa where id = 4;
Query OK, 1 row affected (0.01 sec)
```

```
-- starrocks  2.5.6
mysql> select * from aaa order by id;
+------+------+------+------+
| id   | a    | c    | b    |
+------+------+------+------+
|    5 | b    | b    | b    |
|    6 | c    | c    | c    |
+------+------+------+------+
2 rows in set (0.03 sec)
```
