### ISSUE TITLE
亲，可以提供支持Prometheus监控的接口吗？

### ISSUE THREAD

**Issue by go-lazyer** [liuxinwang/go-mysql-starrocks#6]
线上同步过程中，会因为某种原因down掉了。如果能提供监控接口，那就太完美了。

**Comment by go-lazyer** [comment]
目前碰到两种情况：
1.starrocks重启
2.starrocks和mysql的中文数据长度计算规则不一致，按照mysql的字段长度创建starrocks表后，会导致插入报错。

**Comment by liuxinwang** [comment]
我先集成prometheus基础监控，可以通过端口号监控。 [参考新版本v0.1.13](https://github.com/liuxinwang/go-mysql-starrocks/releases/tag/v0.1.13)
后续再完善其它监控指标，如延迟监控等

**Comment by go-lazyer** [comment]
非常感谢
