### ISSUE TITLE
创建表报错，且新表不在同步的列表中

### ISSUE THREAD

**Issue by go-lazyer** [liuxinwang/go-mysql-starrocks#9]
`[2023/07/13 16:47:37] [info] sync.go:233 table structure changed, clear table cache: daowei.test_tech
[2023/07/13 16:47:47] [info] ip_mysql.go:223 ddl event: ALTER TABLE `daowei`.`test_tech`
ADD COLUMN `d6` varchar(2) NULL AFTER `d5`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9d8454]

goroutine 51 [running]:
github.com/liuxinwang/go-mysql-starrocks/pkg/schema.(*Table).FindColumn(...)
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/schema/schema.go:57
github.com/liuxinwang/go-mysql-starrocks/pkg/schema.(*MysqlTables).UpdateTable(0xc0003de480, {0xc0011766e8?, 0xcb2840?}, {0xc0011766f0, 0x9}, {0xc6faa0, 0xc0006c4c40})
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/schema/sch_mysql.go:103 +0x314
github.com/liuxinwang/go-mysql-starrocks/pkg/input.(*MysqlInputPlugin).parseStmt(0xc0002d9600, {0xf0c880?, 0xc0007b84c0?}, {0xc001176700, 0x6})
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/input/ip_mysql.go:465 +0x523
github.com/liuxinwang/go-mysql-starrocks/pkg/input.(*MysqlInputPlugin).OnDDL(0xc0002d9600, {{0xc000839e50?, 0x6?}, 0x839e56?}, 0xc0003c59d0)
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/input/ip_mysql.go:230 +0x1fb
github.com/go-mysql-org/go-mysql/canal.(*Canal).runSyncBinlog(0xc0002b3b00)
	/Users/wangwuyang/GolandProjects/pkg/mod/github.com/liuxinwang/go-mysql@v1.6.3-enhancement/canal/sync.go:162 +0xbb5
github.com/go-mysql-org/go-mysql/canal.(*Canal).run(0xc0002b3b00)
	/Users/wangwuyang/GolandProjects/pkg/mod/github.com/liuxinwang/go-mysql@v1.6.3-enhancement/canal/canal.go:230 +0x1c5
github.com/go-mysql-org/go-mysql/canal.(*Canal).Run(...)
	/Users/wangwuyang/GolandProjects/pkg/mod/github.com/liuxinwang/go-mysql@v1.6.3-enhancement/canal/canal.go:185
github.com/go-mysql-org/go-mysql/canal.(*Canal).StartFromGTID(0xc0002b3b00, {0xf09078?, 0xc00000e1e0?})
	/Users/wangwuyang/GolandProjects/pkg/mod/github.com/liuxinwang/go-mysql@v1.6.3-enhancement/canal/canal.go:198 +0x39
github.com/liuxinwang/go-mysql-starrocks/pkg/input.(*MysqlInputPlugin).StartInput.func1()
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/input/ip_mysql.go:114 +0x25
created by github.com/liuxinwang/go-mysql-starrocks/pkg/input.(*MysqlInputPlugin).StartInput
	/Users/wangwuyang/GolandProjects/go-mysql-starrocks/pkg/input/ip_mysql.go:113 +0x495`

**Comment by liuxinwang** [comment]
用的哪个版本
